export const FUNCTION_LESSON_MAP: Record<string, string> = {
  's(': '1.1', 'sound(': '1.1', '.bank(': '1.4',
  'euclidean': '2.8', '(beats,': '2.8',
  'note(': '3.1', '.scale(': '3.3', 'n(': '3.3', '.voicings(': '3.6',
  'stack(': '4.1', '.slow(': '4.3', '.fast(': '4.3',
  '.attack(': '5.2', '.decay(': '5.2', '.sustain(': '5.2', '.release(': '5.2',
  '.gain(': '5.3', '.speed(': '5.4', '.cutoff(': '5.5', '.lpf(': '5.5',
  '.room(': '6.1', '.reverb(': '6.1', '.delay(': '6.2',
  '.shape(': '6.3', '.crush(': '6.3', '.pan(': '6.4',
  'sine': '7.1', 'cosine': '7.1', 'perlin': '7.2',
  'rand': '7.3', '.sometimes(': '7.4', '.rarely(': '7.4', '.often(': '7.4',
  '.degradeBy(': '7.4',
}

export const LESSON_TITLE_MAP: Record<string, string> = {
  '1.1': 'Hello, Kick Drum',
  '1.4': 'Drum Machines',
  '2.8': 'Euclidean Rhythms',
  '3.1': 'Note Names',
  '3.3': 'The n() Function',
  '3.6': 'Chord Voicings',
  '4.1': 'Stack Basics',
  '4.3': 'Slow & Fast',
  '5.2': 'ADSR Envelope',
  '5.3': 'Volume',
  '5.4': 'Sample Speed',
  '5.5': 'Filter',
  '6.1': 'Reverb',
  '6.2': 'Delay',
  '6.3': 'Distortion',
  '6.4': 'Panning',
  '7.1': 'Sine Modulation',
  '7.2': 'Perlin Noise',
  '7.3': 'Probability',
  '7.4': 'Sometimes',
}
