import type { Completion } from '@codemirror/autocomplete'

const createCompletion = (label: string, type: Completion['type'], detail: string, info: string): Completion => ({
  label,
  type,
  detail,
  info,
})

const FUNCTION_COMPLETIONS: Completion[] = [
  createCompletion('sound', 'function', 'sound(name: string)', 'Builds a pattern from a sample or synth source string.'),
  createCompletion('note', 'function', 'note(pitch: string | number)', 'Creates a note pattern from note names or note expressions.'),
  createCompletion('n', 'function', 'n(index: number | string)', 'Creates a numeric note pattern using scale-relative values.'),
  createCompletion('s', 'function', 's(name: string)', 'Creates a sample pattern from mini-notation labels.'),
  createCompletion('freq', 'function', 'freq(value: number | Pattern)', 'Creates a pattern of raw oscillator frequencies.'),
  createCompletion('synth', 'function', 'synth(name: string)', 'Selects a synth voice by name for the current pattern.'),
  createCompletion('stack', 'function', 'stack(...patterns)', 'Layers multiple patterns so they play at the same time.'),
  createCompletion('cat', 'function', 'cat(...patterns)', 'Concatenates patterns one after another in sequence.'),
  createCompletion('seq', 'function', 'seq(...patterns)', 'Builds a sequence by stepping through patterns in order.'),
  createCompletion('slowcat', 'function', 'slowcat(...patterns)', 'Concatenates patterns while stretching each one over a full cycle.'),
  createCompletion('fastcat', 'function', 'fastcat(...patterns)', 'Concatenates patterns while fitting them into a single cycle.'),
  createCompletion('rand', 'function', 'rand()', 'Generates a random numeric pattern.'),
  createCompletion('perlin', 'function', 'perlin()', 'Generates smooth Perlin-noise style modulation values.'),
  createCompletion('silence', 'function', 'silence()', 'Produces an empty pattern with no events.'),
  createCompletion('pure', 'function', 'pure(value)', 'Repeats a constant value as a pattern.'),
  createCompletion('isorhythm', 'function', 'isorhythm(rhythm, values)', 'Combines a rhythm pattern with a separate value cycle.'),
  createCompletion('polymeter', 'function', 'polymeter(...patterns)', 'Combines patterns of different lengths into a shared cycle.'),
  createCompletion('polyrhythm', 'function', 'polyrhythm(...patterns)', 'Stacks patterns with independent rhythmic subdivisions.'),
  createCompletion('striate', 'function', 'striate(parts)', 'Slices a sample into equal grains across the cycle.'),
  createCompletion('fast', 'function', 'fast(factor: number | Pattern)', 'Speeds a pattern up by the given factor.'),
  createCompletion('slow', 'function', 'slow(factor: number | Pattern)', 'Slows a pattern down by the given factor.'),
  createCompletion('early', 'function', 'early(time: number)', 'Shifts events earlier in time by a fraction of a cycle.'),
  createCompletion('late', 'function', 'late(time: number)', 'Shifts events later in time by a fraction of a cycle.'),
  createCompletion('zoom', 'function', 'zoom(start, end)', 'Focuses playback on a subsection of the pattern.'),
  createCompletion('compress', 'function', 'compress(start, end)', 'Compresses the pattern into a narrower time window.'),
  createCompletion('linger', 'function', 'linger(amount)', 'Extends event durations to linger longer into the cycle.'),
  createCompletion('segment', 'function', 'segment(n: number)', 'Splits a pattern into evenly sized temporal segments.'),
  createCompletion('struct', 'function', 'struct(pattern: string)', 'Applies a structural rhythm mask to another pattern.'),
  createCompletion('mask', 'function', 'mask(pattern: string)', 'Keeps events only where the mask pattern is active.'),
  createCompletion('euclid', 'function', 'euclid(pulses, steps, offset?)', 'Generates a Euclidean rhythm with evenly distributed pulses.'),
  createCompletion('euclidLegato', 'function', 'euclidLegato(pulses, steps, offset?)', 'Generates a Euclidean rhythm with connected legato events.'),
  createCompletion('apply', 'function', 'apply(transform)', 'Applies a transformation function to a pattern.'),
  createCompletion('applyFirst', 'function', 'applyFirst(transform)', 'Applies a transform to the first layer or branch of a pattern.'),
  createCompletion('applySecond', 'function', 'applySecond(transform)', 'Applies a transform to the second layer or branch of a pattern.'),
  createCompletion('firstOf', 'function', 'firstOf(n, transform)', 'Applies a transform on the first cycle of a repeating block.'),
  createCompletion('lastOf', 'function', 'lastOf(n, transform)', 'Applies a transform on the last cycle of a repeating block.'),
  createCompletion('every', 'function', 'every(n, transform)', 'Applies a transform every N cycles.'),
  createCompletion('sometimesBy', 'function', 'sometimesBy(prob, transform)', 'Applies a transform probabilistically with an explicit chance.'),
  createCompletion('sometimes', 'function', 'sometimes(transform)', 'Occasionally applies a transform to the pattern.'),
  createCompletion('rarely', 'function', 'rarely(transform)', 'Applies a transform only on rare cycles.'),
  createCompletion('often', 'function', 'often(transform)', 'Applies a transform frequently across cycles.'),
  createCompletion('always', 'function', 'always(transform)', 'Applies a transform every time.'),
  createCompletion('never', 'function', 'never(transform)', 'Disables the supplied transform.'),
  createCompletion('almostNever', 'function', 'almostNever(transform)', 'Applies a transform only on very rare cycles.'),
  createCompletion('almostAlways', 'function', 'almostAlways(transform)', 'Applies a transform on nearly every cycle.'),
  createCompletion('degrade', 'function', 'degrade()', 'Randomly removes some events from the pattern.'),
  createCompletion('degradeBy', 'function', 'degradeBy(prob: number)', 'Drops events with the given probability.'),
  createCompletion('undegradeBy', 'function', 'undegradeBy(prob: number)', 'Restores dropped-event density toward the original pattern.'),
  createCompletion('iter', 'function', 'iter(n: number)', 'Rotates pattern content forward over repeated cycles.'),
  createCompletion('iterBack', 'function', 'iterBack(n: number)', 'Rotates pattern content backward over repeated cycles.'),
  createCompletion('rev', 'function', 'rev()', 'Reverses the order of events in the pattern.'),
  createCompletion('palindrome', 'function', 'palindrome()', 'Plays the pattern forward then backward as a mirrored phrase.'),
  createCompletion('superimpose', 'function', 'superimpose(transform)', 'Layers a transformed copy of the pattern on top of itself.'),
  createCompletion('layer', 'function', 'layer(...transforms)', 'Stacks multiple transformed versions of the same pattern.'),
  createCompletion('off', 'function', 'off(time, transform)', 'Layers a time-shifted transformed copy of the pattern.'),
  createCompletion('when', 'function', 'when(condition, transform)', 'Applies a transform only when the condition pattern is true.'),
  createCompletion('while', 'function', 'while(condition, transform)', 'Keeps a transform active while the condition pattern is true.'),
  createCompletion('chunk', 'function', 'chunk(n, transform)', 'Applies a transform to forward-moving chunks of a pattern.'),
  createCompletion('chunkBack', 'function', 'chunkBack(n, transform)', 'Applies a transform to backward-moving chunks of a pattern.'),
  createCompletion('transpose', 'function', 'transpose(semitones: number)', 'Transposes notes by the given interval.'),
  createCompletion('scale', 'function', 'scale(name: string)', 'Quantizes note values to a named scale.'),
  createCompletion('scaleTranspose', 'function', 'scaleTranspose(semitones: number)', 'Transposes within the active scale context.'),
  createCompletion('chord', 'function', 'chord(name: string)', 'Expands notes into a named chord shape.'),
  createCompletion('voicing', 'function', 'voicing(name: string)', 'Applies a voicing arrangement to chord tones.'),
  createCompletion('rootNotes', 'function', 'rootNotes(pattern)', 'Supplies root notes used by scale or chord operations.'),
  createCompletion('mode', 'function', 'mode(name: string)', 'Sets the modal context for note interpretation.'),
  createCompletion('octave', 'function', 'octave(value: number)', 'Places note output in a specific octave.'),
  createCompletion('octs', 'function', 'octs(pattern)', 'Cycles across octave offsets.'),
  createCompletion('gain', 'function', 'gain(amount: number)', 'Sets output amplitude for the pattern.'),
  createCompletion('cutoff', 'function', 'cutoff(freq: number)', 'Controls low-pass filter cutoff frequency.'),
  createCompletion('resonance', 'function', 'resonance(amount: number)', 'Controls low-pass filter resonance.'),
  createCompletion('hcutoff', 'function', 'hcutoff(freq: number)', 'Controls high-pass filter cutoff frequency.'),
  createCompletion('hresonance', 'function', 'hresonance(amount: number)', 'Controls high-pass filter resonance.'),
  createCompletion('bandf', 'function', 'bandf(freq: number)', 'Sets the center frequency of a band-pass filter.'),
  createCompletion('bandq', 'function', 'bandq(q: number)', 'Sets the Q or sharpness of a band-pass filter.'),
  createCompletion('shape', 'function', 'shape(amount: number)', 'Applies wave shaping distortion.'),
  createCompletion('coarse', 'function', 'coarse(factor: number)', 'Reduces pitch or playback resolution in coarse steps.'),
  createCompletion('crush', 'function', 'crush(bits: number)', 'Applies bit crushing to the signal.'),
  createCompletion('distort', 'function', 'distort(amount: number)', 'Adds distortion to the sound.'),
  createCompletion('pan', 'function', 'pan(amount: number)', 'Places sound in the stereo field.'),
  createCompletion('panning', 'function', 'panning(amount: number)', 'Provides an alternate stereo panning control.'),
  createCompletion('room', 'function', 'room(amount: number)', 'Sets reverb amount.'),
  createCompletion('size', 'function', 'size(amount: number)', 'Sets reverb room size.'),
  createCompletion('delay', 'function', 'delay(amount: number)', 'Sets delay send amount.'),
  createCompletion('delaytime', 'function', 'delaytime(time: number)', 'Sets the delay time.'),
  createCompletion('delayfeedback', 'function', 'delayfeedback(amount: number)', 'Sets delay feedback amount.'),
  createCompletion('orbit', 'function', 'orbit(n: number)', 'Routes a pattern to a specific mixer orbit.'),
  createCompletion('velocity', 'function', 'velocity(amount: number)', 'Sets note velocity or dynamic intensity.'),
  createCompletion('attack', 'function', 'attack(seconds: number)', 'Sets envelope attack time.'),
  createCompletion('decay', 'function', 'decay(seconds: number)', 'Sets envelope decay time.'),
  createCompletion('sustain', 'function', 'sustain(level: number)', 'Sets envelope sustain level.'),
  createCompletion('release', 'function', 'release(seconds: number)', 'Sets envelope release time.'),
  createCompletion('tremolo', 'function', 'tremolo(rate: number)', 'Applies amplitude tremolo at a given rate.'),
  createCompletion('tremolodepth', 'function', 'tremolodepth(amount: number)', 'Sets tremolo modulation depth.'),
  createCompletion('vowel', 'function', 'vowel(formant: string)', 'Applies a vowel-like formant coloration.'),
  createCompletion('speed', 'function', 'speed(rate: number)', 'Changes sample playback speed.'),
  createCompletion('begin', 'function', 'begin(pos: number)', 'Sets the playback start point within a sample.'),
  createCompletion('end', 'function', 'end(pos: number)', 'Sets the playback end point within a sample.'),
  createCompletion('loop', 'function', 'loop(on: 0 | 1)', 'Enables or disables looping for sample playback.'),
  createCompletion('loopBegin', 'function', 'loopBegin(pos: number)', 'Sets the start point for sample looping.'),
  createCompletion('loopEnd', 'function', 'loopEnd(pos: number)', 'Sets the end point for sample looping.'),
  createCompletion('cut', 'function', 'cut(group: number)', 'Applies cut-group behavior for sample choking.'),
  createCompletion('unit', 'function', 'unit(name: string)', 'Sets the unit used for interpreting pattern values.'),
  createCompletion('clip', 'function', 'clip(amount: number)', 'Clamps or clips signal amplitude.'),
  createCompletion('leslie', 'function', 'leslie(amount: number)', 'Applies a Leslie speaker-style rotary effect.'),
  createCompletion('lrate', 'function', 'lrate(rate: number)', 'Sets Leslie rotation rate.'),
  createCompletion('lsize', 'function', 'lsize(amount: number)', 'Sets Leslie effect size or spread.'),
  createCompletion('phaser', 'function', 'phaser(amount: number)', 'Applies a phaser effect.'),
  createCompletion('phaserrate', 'function', 'phaserrate(rate: number)', 'Sets phaser sweep rate.'),
  createCompletion('phaserdepth', 'function', 'phaserdepth(amount: number)', 'Sets phaser modulation depth.'),
]

const KEYWORD_COMPLETIONS: Completion[] = [
  createCompletion('bd', 'keyword', 'sample bank name', 'Refers to the kick drum sample bank label in mini-notation.'),
  createCompletion('sd', 'keyword', 'sample bank name', 'Refers to the snare drum sample bank label in mini-notation.'),
  createCompletion('hh', 'keyword', 'sample bank name', 'Refers to the closed hi-hat sample bank label in mini-notation.'),
  createCompletion('oh', 'keyword', 'sample bank name', 'Refers to the open hi-hat sample bank label in mini-notation.'),
  createCompletion('cp', 'keyword', 'sample bank name', 'Refers to the clap sample bank label in mini-notation.'),
  createCompletion('cr', 'keyword', 'sample bank name', 'Refers to the crash cymbal sample bank label in mini-notation.'),
  createCompletion('lt', 'keyword', 'sample bank name', 'Refers to the low tom sample bank label in mini-notation.'),
  createCompletion('mt', 'keyword', 'sample bank name', 'Refers to the mid tom sample bank label in mini-notation.'),
  createCompletion('ht', 'keyword', 'sample bank name', 'Refers to the high tom sample bank label in mini-notation.'),
  createCompletion('rd', 'keyword', 'sample bank name', 'Refers to the ride cymbal sample bank label in mini-notation.'),
  createCompletion('rim', 'keyword', 'sample bank name', 'Refers to the rimshot sample bank label in mini-notation.'),
  createCompletion('cb', 'keyword', 'sample bank name', 'Refers to the cowbell sample bank label in mini-notation.'),
  createCompletion('sh', 'keyword', 'sample bank name', 'Refers to the shaker sample bank label in mini-notation.'),
  createCompletion('tb', 'keyword', 'sample bank name', 'Refers to the tambourine sample bank label in mini-notation.'),
  createCompletion('misc', 'keyword', 'sample bank name', 'Refers to the miscellaneous percussion sample bank label in mini-notation.'),
  createCompletion('<...>', 'keyword', '<a b c>', 'Alternates values inside angle brackets over time.'),
  createCompletion('[...]', 'keyword', '[a b c]', 'Groups mini-notation events into a subdivided sequence.'),
  createCompletion('{...}~', 'keyword', '{a b}~', 'Creates a polymetric or offset grouping pattern fragment.'),
  createCompletion('!', 'keyword', 'pattern!', 'Replicates the previous mini-notation event or group.'),
  createCompletion('@', 'keyword', 'event@weight', 'Weights a mini-notation event relative to its neighbors.'),
  createCompletion('?', 'keyword', 'event?', 'Marks a mini-notation event for probabilistic degradation.'),
]

const METHOD_COMPLETIONS: Completion[] = FUNCTION_COMPLETIONS.map((completion) => ({
  ...completion,
  type: 'method',
  detail: typeof completion.detail === 'string' && completion.detail.includes('(')
    ? completion.detail.slice(completion.detail.indexOf('('))
    : `.${completion.label}()`,
}))

export const STRUDEL_COMPLETIONS: Completion[] = [
  ...FUNCTION_COMPLETIONS,
  ...METHOD_COMPLETIONS,
  ...KEYWORD_COMPLETIONS,
]
